version: '3.1'

services:

  mongo:
    container_name: database
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    logging:
      driver: none

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/test

  app:
    build: .
    container_name: aluguel_de_carro
    restart: always
    ports: 
      - 8080:8080
    volumes:
      - .:/usr/app
    links:
      - mongo